### PR TITLE
Add support for git knowing only mac output.

### LINKED ISSUE #9: support git versions

### PR DESCRIPTION
**Pull request by Kineolyan**
This will close #9 .
So far, I need access to a unix output and windows output to add to the tests.
It as also better to wait for the merge of PRs #32 and #16 before merging.

### CODE REVIEW

**Comment by fabiencelier** [comment]
On my ubuntu : 
```bash
>>> git --version
git version 2.20.1
```

**Comment by fabiencelier** [comment]
Here is one on windows 8 : 
```
>>> git --version
git version 2.24.0.windows.1
```

**Comment by fabiencelier** [comment]
Searching for "git --version" or google I have also found these : 
 - `git version 1.9.5.msysgit.0` [here](http://modulesunraveled.com/installing-git/checking-see-if-you-already-have-git-installed-windows-machine) 
 - `git version 1.7.7.3` [here](https://confluence.atlassian.com/crucible042/installing-and-upgrading-git-869175555.html)

[Latest version](https://github.com/git/git/tags) seems to follow semver

**Comment by Kineolyan** [comment]
The PR is now working for all kinds of output.

**Pull request merged**
